### ISSUE TITLE
MaAI Job Portal (tracker issue)

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#423]
### Background
The situation is that the Master AI students (MaAI) at FAU (but many of the other international students at FAU) work or intern at the technology companies (Fraunhofer, Siemens, Schaeffler, Addidas, Puma, may be the ones you have heard about, but there are many more) in the Erlangen-Nürnberg metropolitan region.   

At the same time, the university has great difficulties of providing German courses to international students that would make them more integrated into German society, more useful to the companies, and more likely to join the German labor force (who is always complaining about shortages of qualified personell)

### Basic Idea
I want to have a FAU-centered Job Portal that all the MaAI students can subscribe to where companies (let's call them the **MaAI friends**) post their job ads to them, and we get the data of how successful they are in filling their jobs (telling us about this is one of the prerequisites of staying a MaAI friend). 

### More background
We have polled the MaAI students of where/if they work, and (from memory) almost half has a job with a company in the region, and even if we subtract Amazon it is still about 1/3. So there seems to be a market for our MaAI students. And I have one piece of anecdotal evidence: A person at Schaeffler who had helped us  with re-accreditation had asked whether we could pass on a job ad (which we did because he was a MaAI friend before we coined the term just now) and a week later he contacted us with a "thanks this worked extremely well, we had 4 applications within 24 hours, and we could have hired all of them". 

### Crucial Angle and Leverage
If we have data that the recruiting for one of the companies is going well, we will approach them with the request: "*We know that on average recruiting for a student job position costs $X$ kEuro, so by our records you have $Y$ kEuro, so please spend 20% of that for sponsoring language courses for the international students. This is a Win-Win Situation: you invest into the usefulness of the labour force, and we graduate better-qualified students*". 

I think that this just might work, and I have already talked to some of the people; who are all enthusiastic about the idea so far:

* the CEO of the language courses center at FAU who would love to teach our students, but does not have funding.
* the upcoming dean of engineering, who is already involved in organizing language courses for the Ph.D. students and would like to offer the Master's students something similar
* I still have to pitch the idea to some of the companies. But maybe I want to build the system first. 

### In the long run
I would like to couple this job market (good name still missing) with ALeA. I would like to set up a feature in there, where the students can (with the click of a button) put their learner models into a "LM escrow" that can be queried by selected companies they are applying to. Then the companies can get insights about the qualifications/competencies while the actual learner models stay safe in the LMP. That would be an innovative feature for the companies to experiment with and would maybe make it more attractive for students to invest into expressive learner models. 
But this is a separate research project for the future. 

### What we need:
I do think that we have many of the parts we need in hand already in ALeA. Initially, we need
- [ ]  IDM login for the students, and a list of the students in the technology fields we can restrict access to.
- [ ] e-mail authentication for the company reps; the FAU Friends (moderated by someone like me or the Department manager)
- [ ] a notification for the students (this could become part of the student dashboard in ALeA).
- [ ] submission facilities for (probably HTML) job ads and the necessary metadata (type of job, number of positions, qualifications).
- [ ] job application submission facilities for the students. They could actually be supported in doing a resume, ... in the system (which would be interesting data for ALeA that could be correlated to other things).

The more I think about it, I think I would like it integrated into ALeA because of the data synergies.

**Comment by kohlhase** [comment]
We have a [design document](https://docs.google.com/document/d/1DMR2SkuTrfxabdM0r-irWjDTmpwBAWhpb-KcxX6WsJ0/edit?tab=t.0#heading=h.1wuhzfootwb3) Abhishek looked at  portals in other institutions.

**Comment by kohlhase** [comment]
Frederik noted that the job portal might be a very good way of distributing master's theses transparently.
