### ISSUE TITLE
Tracker: flash card tweaks

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#43]
There are a couple of tweaks that (I think) would improve flash cards practically: 
- [x] the new flip icon should have a hover "flip the card to see the definition" (on the front) and "flip it back" 
- [x] I do not see the difference between "drill me" and "revise". Maybe they should have hovers that explain what you get? 
- [x] the concept list at https://pastebin.com/raw/QakUfMgh @abchugh gave me has 1044 entries for AI-1, but https://courses.voll-ki.fau.de/flash-cards/ai-1 only lists 470 (for IWGS the count is correct).  
- [x] I would like the cards a bit more wide (at least for wieder screens). The traditional cards are A6 or A7 horizontal. That would also alleviate the text alignment problems a bit. 
- [x] We need an intro text for flash cards (though I do not know where to put it). I used *Flash Cards are an experimental VoLL-KI service that supports reviewing and drilling the concepts of the AI-1 course. Learners are randomly shown cards with concept names that can be flipped to view the definition. Learners can self-assess their concept mastery, updating the VoLL-KI learner model, which in turn affects the cards shown in a drill.* for the studon link. 
- [x] We need a treatment for **synonyms**: sometimes we have synonyms in the definitions (e.g. **sound** and **correct**) then the flash card should have both on the front (or even **sound** = **correct**).
- [x] **drill configurator**; see #43
- [x] **drill countdown**; we currently see something like `2 of 39` in the right upper hand corner 
- [x] **drill summary**: when we have exhausted the cards in a drill, we need a summary, the current one does not seem to work: I self-assessed positively and it said `you remembered 0...` This should completely be rethought wrt. the learner model.

**Comment by abchugh** [comment]
>  the concept list at https://pastebin.com/raw/QakUfMgh @abchugh gave me has 1044 entries for AI-1, but https://courses.voll-ki.fau.de/flash-cards/ai-1 only lists 470 (for IWGS the count is correct).
1044 is the total number of concepts from ai-1 and ai-2
There are now 600 (up from 477) concepts in the flash cards (up to 'Knowledge Representation and the Semantic Web')

**Comment by kohlhase** [comment]
Thanks for the clarification. 
I was previously not aware that you needed manual sectioning.

**Comment by abchugh** [comment]
Made a few fixes. Making separate issue (#60) for remaining (long-term) fixes.

> I do not see the difference between "drill me" and "revise". Maybe they should have hovers that explain what you get?

At a high level, in the "revise" mode the interface tries to mimic the experience where you have cards in your hand to learn/revise the concepts. In the "drill" mode we try to mimic the scenario where the cards are in your friend/instructor's hand and they ask you to recall the concepts. Specifically, in "Revise" mode you can browse through the cards more freely while in "Drill" you can only move the cards forward, and ending a drill early is discouraged. "Drills" additionally can have shuffled cards and a summary page of your performance.

>  drill countdown; we currently see something like 2 of 39 in the right upper hand corner

I believe that the primary use case was the scenario where drills end early (eg. in demos). Now, the summary card is shown even when when a drill is end early.
