### ISSUE TITLE
Tracker: User note/comments  tweaks

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#49]
I want to use this issue to collect proposed tweaks to the notes/comments feature: 
- [x] There should be explanatory text, e.g. in the help/manual (I will write that, see #48) that explains the facilities
- [x] notes/comments should have a type (question, answer, correction, ...)
- [x] comment threads should have a type (open/ongoing, closed, resolved, ...)
- [x] **this is the main problem** the UI should indicate the presence (and maybe the gravity/recency) of the notes in place, e.g. on the right of the content they are localized to! 
- [x] management features for the "all comments" page (https://courses.voll-ki.fau.de/all-comments), for instance I would like to be able to hide or collapse threads, hide them, ... so that I know what I still have to answer, ...  The notes/thread types could help here, i.e. e.g. threads are only shown if they are not resolved. 

[Not planned soon] notes/comments are currently localized to the course notes or slides. They should be attached to the semantic concepts, so that they can also appear in the guided tours or other generated content.

**Comment by abchugh** [comment]
With the forum view, most of the above is solved. 

The manual has some documentation about the comments https://gl.mathhub.info/voll-ki/ALeA/-/tree/main/source/doc. But that may need to be updated.

The localization of comments to semantic concepts is a significantly large project - not something we plan to do anytime soon.
